# Generated by Django 5.2.10 on 2026-02-04 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'quotes_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unpaid', 'Non payée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='unpaid', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='quotes.order')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'quotes_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('batiment', 'Bâtiment'), ('industriel', 'Industriel')], default='batiment', max_length=20)),
                ('zone', models.CharField(choices=[('interieur', 'Intérieur'), ('exterieur', 'Extérieur')], default='interieur', max_length=20)),
                ('element', models.CharField(choices=[('mur', 'Mur'), ('plafond', 'Plafond')], default='mur', max_length=20)),
                ('surface', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plafond_type', models.CharField(blank=True, choices=[('placo', 'Placo'), ('enduit_ciment', 'Enduit Ciment'), ('ancien_peinture', 'Ancien Peinturé'), ('platre_projete', 'Plâtre Projeté')], default='placo', max_length=20)),
                ('placo_fini', models.BooleanField(default=True)),
                ('finition_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('decorative', 'Décorative')], default='simple', max_length=20)),
                ('peinture_aspect', models.CharField(blank=True, choices=[('mat', 'Mat'), ('satine', 'Satiné'), ('brillant', 'Brillant')], default='satine', max_length=20)),
                ('decorative_option', models.CharField(blank=True, choices=[('produit_decoratif', 'Produit Décoratif'), ('papier_peint', 'Papier Peint')], default='produit_decoratif', max_length=20)),
                ('system_key', models.CharField(blank=True, default='', max_length=50)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('client_address', models.TextField(blank=True, default='')),
                ('client_phone', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'quotes_quote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='quotes.quote'),
        ),
        migrations.CreateModel(
            name='QuoteMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quotes.quote')),
            ],
            options={
                'db_table': 'quotes_material',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSystemStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_steps', to='quotes.quote')),
            ],
            options={
                'db_table': 'quotes_system_step',
                'ordering': ['order'],
            },
        ),
    ]
