# Generated by Django 5.2.10 on 2026-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='ancien_enduit',
            field=models.CharField(blank=True, choices=[('avec_enduit', 'Avec Enduit'), ('sans_enduit', 'Sans Enduit')], default='avec_enduit', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='exterieur_finition',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('decoratif', 'Décoratif')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='exterieur_type',
            field=models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('monocouche', 'Monocouche'), ('ancien_peinture', 'Ancien Peinturé'), ('placo', 'Placo')], default='neuf', max_length=20),
        ),
    ]
