# Generated by Django 5.2.10 on 2026-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_ancien_enduit_quote_exterieur_finition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesystemstep',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
