# Generated by Django 5.2.10 on 2026-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quotesystemstep_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='selected_enduit',
            field=models.CharField(blank=True, default='jeton_prefix_putty', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='selected_finition',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='selected_impression',
            field=models.CharField(blank=True, default='pva_primer', max_length=50),
        ),
    ]
