# Generated by Django 5.2.10 on 2026-02-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_selected_enduit_quote_selected_finition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='selected_decoratif',
            field=models.CharField(blank=True, default='lady_design_purple', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='selected_decoratif_size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
